//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAL.Developer.Test.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblTimesheets = new HashSet<tblTimesheet>();
        }
    
        public int empId { get; set; }
        public string empName { get; set; }
        public string empUsername { get; set; }
        public string empPassword { get; set; }
        public int empGroupId { get; set; }
        public int empTimezoneId { get; set; }
        public decimal empRate { get; set; }
    
        public virtual tblGroup tblGroup { get; set; }
        public virtual tblTimezone tblTimezone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTimesheet> tblTimesheets { get; set; }
    }
}
