//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAL.Developer.Test.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMember
    {
        public int memId { get; set; }
        public string memName { get; set; }
        public System.DateTime memDOB { get; set; }
        public int memOccupationId { get; set; }
        public decimal memSumInsured { get; set; }
    
        public virtual tblOccupation tblOccupation { get; set; }
    }
}
