//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAL.Developer.Test.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOccupation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblOccupation()
        {
            this.tblMembers = new HashSet<tblMember>();
        }
    
        public int occId { get; set; }
        public string occName { get; set; }
        public int occOccupationRatingId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMember> tblMembers { get; set; }
        public virtual tblOccupationRating tblOccupationRating { get; set; }
    }
}
