//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TAL.Developer.Test.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimesheet
    {
        public int tshId { get; set; }
        public int tshEmployeeId { get; set; }
        public int tshTimezoneId { get; set; }
        public System.DateTime tshStartDate { get; set; }
        public Nullable<System.DateTime> tshEndDate { get; set; }
        public decimal tshRate { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblTimezone tblTimezone { get; set; }
    }
}
